# Generated by Django 5.2.6 on 2025-09-17 08:35

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(choices=[('user_query', 'User Query'), ('research_lab', 'Research Lab')], default='user_query', max_length=50)),
                ('user_input', models.JSONField(default=dict)),
                ('generated_result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('algorithm_version', models.CharField(default='v1.0.1', max_length=22)),
            ],
        ),
    ]
